// Team metadata stays independent of Vite so verification can inspect every club.
export const SPORTS_CLUBS = {
  "yankees": {
    "name": "New York Yankees",
    "short": "Yankees",
    "city": "New York",
    "sport": "Baseball",
    "motto": "BRONX BASEBALL",
    "label": "NY Yankees",
    "description": "Bronx nights, Monument Park legends, and pinstripes under the lights.",
    "logoSource": "https://www.mlbstatic.com/team-logos/147.svg"
  },
  "giants": {
    "name": "New York Giants",
    "short": "Giants",
    "city": "New York",
    "sport": "Football",
    "motto": "BIG BLUE",
    "label": "NY Giants",
    "description": "Big Blue under the lights. Royal blue and red.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/NYG"
  },
  "knicks": {
    "name": "New York Knicks",
    "short": "Knicks",
    "city": "New York",
    "sport": "Basketball",
    "motto": "GARDEN NIGHTS",
    "label": "NY Knicks",
    "description": "Garden nights. Electric blue, orange, and hardwood.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg"
  },
  "dodgers": {
    "name": "Los Angeles Dodgers",
    "short": "Dodgers",
    "city": "Los Angeles",
    "sport": "Baseball",
    "motto": "DODGER BLUE",
    "label": "LA Dodgers",
    "description": "Dodger blue, ivory jerseys, and a twilight ballpark.",
    "logoSource": "https://www.mlbstatic.com/team-logos/119.svg",
    "primary": "#005a9c",
    "secondary": "#ef3e42",
    "accent": "#b7dcff",
    "material": "porcelain"
  },
  "red-sox": {
    "name": "Boston Red Sox",
    "short": "Red Sox",
    "city": "Boston",
    "sport": "Baseball",
    "motto": "FENWAY NIGHTS",
    "label": "Boston Red Sox",
    "description": "Fenway brick, deep navy, and heritage red.",
    "logoSource": "https://www.mlbstatic.com/team-logos/111.svg",
    "primary": "#bd3039",
    "secondary": "#0c2340",
    "accent": "#ffbfc3",
    "material": "dark"
  },
  "blue-jays": {
    "name": "Toronto Blue Jays",
    "short": "Blue Jays",
    "city": "Toronto",
    "sport": "Baseball",
    "motto": "NORTH OF ORDINARY",
    "label": "Toronto Blue Jays",
    "description": "Royal blue, maple red, and silver under the dome.",
    "logoSource": "https://www.mlbstatic.com/team-logos/141.svg",
    "primary": "#134a8e",
    "secondary": "#e8291c",
    "accent": "#b8dcff",
    "material": "porcelain"
  },
  "cubs": {
    "name": "Chicago Cubs",
    "short": "Cubs",
    "city": "Chicago",
    "sport": "Baseball",
    "motto": "WRIGLEY CLASSIC",
    "label": "Chicago Cubs",
    "description": "Cubbie blue, bright red, and ivy-lined heritage.",
    "logoSource": "https://www.mlbstatic.com/team-logos/112.svg",
    "primary": "#0e3386",
    "secondary": "#cc3433",
    "accent": "#c4d7ff",
    "material": "porcelain"
  },
  "lakers": {
    "name": "Los Angeles Lakers",
    "short": "Lakers",
    "city": "Los Angeles",
    "sport": "Basketball",
    "motto": "PURPLE & GOLD",
    "label": "LA Lakers",
    "description": "Purple velvet, championship gold, and arena light.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg",
    "primary": "#552583",
    "secondary": "#fdb927",
    "accent": "#ffe2a4",
    "material": "dark"
  },
  "warriors": {
    "name": "Golden State Warriors",
    "short": "Warriors",
    "city": "San Francisco",
    "sport": "Basketball",
    "motto": "GOLDEN STATE",
    "label": "GS Warriors",
    "description": "Bay blue, luminous gold, and bridge geometry.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg",
    "primary": "#1d428a",
    "secondary": "#ffc72c",
    "accent": "#ffe59a",
    "material": "dark"
  },
  "bulls": {
    "name": "Chicago Bulls",
    "short": "Bulls",
    "city": "Chicago",
    "sport": "Basketball",
    "motto": "CHICAGO RED",
    "label": "Chicago Bulls",
    "description": "Black steel, Bulls red, and hardwood precision.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg",
    "primary": "#ce1141",
    "secondary": "#171717",
    "accent": "#ffbecd",
    "material": "dark"
  },
  "cavaliers": {
    "name": "Cleveland Cavaliers",
    "short": "Cavaliers",
    "city": "Cleveland",
    "sport": "Basketball",
    "motto": "WINE & GOLD",
    "label": "Cleveland Cavaliers",
    "description": "Wine enamel, brushed gold, and Cleveland nights.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg",
    "primary": "#860038",
    "secondary": "#fdbb30",
    "accent": "#ffe1a2",
    "material": "dark"
  },
  "heat": {
    "name": "Miami Heat",
    "short": "Heat",
    "city": "Miami",
    "sport": "Basketball",
    "motto": "MIAMI HEAT",
    "label": "Miami Heat",
    "description": "Black glass, burning red, and warm gold.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg",
    "primary": "#98002e",
    "secondary": "#f9a01b",
    "accent": "#ffd6a1",
    "material": "dark"
  },
  "cowboys": {
    "name": "Dallas Cowboys",
    "short": "Cowboys",
    "city": "Dallas",
    "sport": "Football",
    "motto": "DALLAS SILVER",
    "label": "Dallas Cowboys",
    "description": "Midnight blue, silver armor, and dome lights.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/DAL",
    "primary": "#003594",
    "secondary": "#869397",
    "accent": "#d7e5f7",
    "material": "porcelain"
  },
  "eagles": {
    "name": "Philadelphia Eagles",
    "short": "Eagles",
    "city": "Philadelphia",
    "sport": "Football",
    "motto": "MIDNIGHT GREEN",
    "label": "Philadelphia Eagles",
    "description": "Midnight green, platinum, and stadium floodlights.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/PHI",
    "primary": "#004c54",
    "secondary": "#a5acaf",
    "accent": "#b8eee3",
    "material": "dark"
  },
  "patriots": {
    "name": "New England Patriots",
    "short": "Patriots",
    "city": "New England",
    "sport": "Football",
    "motto": "NEW ENGLAND",
    "label": "NE Patriots",
    "description": "Patriot navy, red, and finely brushed silver.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/NE",
    "primary": "#002244",
    "secondary": "#c60c30",
    "accent": "#cbdfff",
    "material": "dark"
  },
  "chiefs": {
    "name": "Kansas City Chiefs",
    "short": "Chiefs",
    "city": "Kansas City",
    "sport": "Football",
    "motto": "ARROWHEAD NIGHTS",
    "label": "KC Chiefs",
    "description": "Arrowhead red, stadium gold, and bold field lines.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/KC",
    "primary": "#e31837",
    "secondary": "#ffb81c",
    "accent": "#ffd7a1",
    "material": "dark"
  },
  "steelers": {
    "name": "Pittsburgh Steelers",
    "short": "Steelers",
    "city": "Pittsburgh",
    "sport": "Football",
    "motto": "STEEL & GOLD",
    "label": "Pittsburgh Steelers",
    "description": "Forged black, bright gold, and steel-city detail.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/PIT",
    "primary": "#171717",
    "secondary": "#ffb612",
    "accent": "#ffe28f",
    "material": "dark"
  },
  "rangers": {
    "name": "New York Rangers",
    "short": "Rangers",
    "city": "New York",
    "sport": "Hockey",
    "motto": "BROADWAY BLUE",
    "label": "NY Rangers",
    "description": "Broadway blue, red trim, and luminous Garden ice.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/NYR_dark.svg",
    "primary": "#0038a8",
    "secondary": "#ce1126",
    "accent": "#c9deff",
    "material": "ice"
  },
  "blackhawks": {
    "name": "Chicago Blackhawks",
    "short": "Blackhawks",
    "city": "Chicago",
    "sport": "Hockey",
    "motto": "CHICAGO ICE",
    "label": "Chicago Blackhawks",
    "description": "Red enamel, black steel, and crisp rink geometry.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/CHI_dark.svg",
    "primary": "#cf0a2c",
    "secondary": "#111111",
    "accent": "#ffbdc7",
    "material": "dark"
  },
  "penguins": {
    "name": "Pittsburgh Penguins",
    "short": "Penguins",
    "city": "Pittsburgh",
    "sport": "Hockey",
    "motto": "BLACK & GOLD",
    "label": "Pittsburgh Penguins",
    "description": "Pittsburgh gold, carbon black, and frozen silver.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/PIT_dark.svg",
    "primary": "#111111",
    "secondary": "#ffb81c",
    "accent": "#ffe399",
    "material": "dark"
  },
  "bruins": {
    "name": "Boston Bruins",
    "short": "Bruins",
    "city": "Boston",
    "sport": "Hockey",
    "motto": "BOSTON GOLD",
    "label": "Boston Bruins",
    "description": "Black and gold, heritage rings, and Garden ice.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg",
    "primary": "#111111",
    "secondary": "#ffb81c",
    "accent": "#ffe59f",
    "material": "ice"
  },
  "maple-leafs": {
    "name": "Toronto Maple Leafs",
    "short": "Maple Leafs",
    "city": "Toronto",
    "sport": "Hockey",
    "motto": "TORONTO BLUE",
    "label": "Toronto Maple Leafs",
    "description": "Toronto blue, winter white, and maple engraving.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg",
    "primary": "#00205b",
    "secondary": "#ffffff",
    "accent": "#c8ddff",
    "material": "ice"
  },
  "canadiens": {
    "name": "Montreal Canadiens",
    "short": "Canadiens",
    "city": "Montreal",
    "sport": "Hockey",
    "motto": "BLEU BLANC ROUGE",
    "label": "Montreal Canadiens",
    "description": "Heritage red, royal blue, and polished white ice.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg",
    "primary": "#af1e2d",
    "secondary": "#192168",
    "accent": "#ffc6ce",
    "material": "ice"
  },
  "mets": {
    "name": "New York Mets", "short": "Mets", "city": "Queens, New York", "sport": "Baseball",
    "motto": "QUEENS · NEW YORK", "label": "NY Mets",
    "description": "Queens after dark. Citi Field brick, cobalt enamel, and Mets orange.",
    "logoSource": "https://www.mlbstatic.com/team-logos/121.svg",
    "material": "bespoke"
  }
};

export const SPORTS_GROUPS = [
  {
    "id": "baseball",
    "label": "Baseball",
    "themes": [
      "yankees",
      "mets",
      "dodgers",
      "red-sox",
      "blue-jays",
      "cubs"
    ]
  },
  {
    "id": "basketball",
    "label": "Basketball",
    "themes": [
      "knicks",
      "lakers",
      "warriors",
      "bulls",
      "cavaliers",
      "heat"
    ]
  },
  {
    "id": "football",
    "label": "Football",
    "themes": [
      "giants",
      "cowboys",
      "eagles",
      "patriots",
      "chiefs",
      "steelers"
    ]
  },
  {
    "id": "hockey",
    "label": "Hockey",
    "themes": [
      "rangers",
      "blackhawks",
      "penguins",
      "bruins",
      "maple-leafs",
      "canadiens"
    ]
  }
];
