// Team metadata stays independent of Vite so verification can inspect every club.
export const SPORTS_CLUBS = {
  "yankees": {
    "established": 1903, "venue": "Yankee Stadium", "opened": 2009, "titles": 27,
    "name": "New York Yankees",
    "short": "Yankees",
    "city": "New York",
    "sport": "Baseball",
    "label": "NY Yankees",
    "description": "Est. 1903. Yankee Stadium opened 2009.",
    "logoSource": "https://www.mlbstatic.com/team-logos/147.svg"
  },
  "giants": {
    "established": 1925, "venue": "MetLife Stadium", "opened": 2010, "titles": 4,
    "name": "New York Giants",
    "short": "Giants",
    "city": "New York",
    "sport": "Football",
    "label": "NY Giants",
    "description": "Est. 1925. MetLife Stadium opened 2010.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/NYG"
  },
  "knicks": {
    "established": 1946, "venue": "Madison Square Garden", "opened": 1968, "titles": 3,
    "name": "New York Knicks",
    "short": "Knicks",
    "city": "New York",
    "sport": "Basketball",
    "label": "NY Knicks",
    "description": "Est. 1946. Madison Square Garden opened 1968.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg"
  },
  "dodgers": {
    "established": 1883, "venue": "Dodger Stadium", "opened": 1962, "titles": 9,
    "name": "Los Angeles Dodgers",
    "short": "Dodgers",
    "city": "Los Angeles",
    "sport": "Baseball",
    "label": "LA Dodgers",
    "description": "Est. 1883. Dodger Stadium opened 1962.",
    "logoSource": "https://www.mlbstatic.com/team-logos/119.svg",
    "primary": "#005a9c",
    "secondary": "#ef3e42",
    "accent": "#b7dcff",
    "material": "porcelain"
  },
  "red-sox": {
    "established": 1901, "venue": "Fenway Park", "opened": 1912, "titles": 9,
    "name": "Boston Red Sox",
    "short": "Red Sox",
    "city": "Boston",
    "sport": "Baseball",
    "label": "Boston Red Sox",
    "description": "Est. 1901. Fenway Park opened 1912.",
    "logoSource": "https://www.mlbstatic.com/team-logos/111.svg",
    "primary": "#bd3039",
    "secondary": "#0c2340",
    "accent": "#ffbfc3",
    "material": "dark"
  },
  "blue-jays": {
    "established": 1977, "venue": "Rogers Centre", "opened": 1989, "titles": 2,
    "name": "Toronto Blue Jays",
    "short": "Blue Jays",
    "city": "Toronto",
    "sport": "Baseball",
    "label": "Toronto Blue Jays",
    "description": "Est. 1977. Rogers Centre opened 1989.",
    "logoSource": "https://www.mlbstatic.com/team-logos/141.svg",
    "primary": "#134a8e",
    "secondary": "#e8291c",
    "accent": "#b8dcff",
    "material": "porcelain"
  },
  "cubs": {
    "established": 1876, "venue": "Wrigley Field", "opened": 1914, "titles": 3,
    "name": "Chicago Cubs",
    "short": "Cubs",
    "city": "Chicago",
    "sport": "Baseball",
    "label": "Chicago Cubs",
    "description": "Est. 1876. Wrigley Field opened 1914.",
    "logoSource": "https://www.mlbstatic.com/team-logos/112.svg",
    "primary": "#0e3386",
    "secondary": "#cc3433",
    "accent": "#c4d7ff",
    "material": "porcelain"
  },
  "lakers": {
    "established": 1947, "venue": "Crypto.com Arena", "opened": 1999, "titles": 17,
    "name": "Los Angeles Lakers",
    "short": "Lakers",
    "city": "Los Angeles",
    "sport": "Basketball",
    "label": "LA Lakers",
    "description": "Est. 1947. Crypto.com Arena opened 1999.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg",
    "primary": "#552583",
    "secondary": "#fdb927",
    "accent": "#ffe2a4",
    "material": "dark"
  },
  "warriors": {
    "established": 1946, "venue": "Chase Center", "opened": 2019, "titles": 7,
    "name": "Golden State Warriors",
    "short": "Warriors",
    "city": "San Francisco",
    "sport": "Basketball",
    "label": "GS Warriors",
    "description": "Est. 1946. Chase Center opened 2019.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg",
    "primary": "#1d428a",
    "secondary": "#ffc72c",
    "accent": "#ffe59a",
    "material": "dark"
  },
  "bulls": {
    "established": 1966, "venue": "United Center", "opened": 1994, "titles": 6,
    "name": "Chicago Bulls",
    "short": "Bulls",
    "city": "Chicago",
    "sport": "Basketball",
    "label": "Chicago Bulls",
    "description": "Est. 1966. United Center opened 1994.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg",
    "primary": "#ce1141",
    "secondary": "#171717",
    "accent": "#ffbecd",
    "material": "dark"
  },
  "cavaliers": {
    "established": 1970, "venue": "Rocket Arena", "opened": 1994, "titles": 1,
    "name": "Cleveland Cavaliers",
    "short": "Cavaliers",
    "city": "Cleveland",
    "sport": "Basketball",
    "label": "Cleveland Cavaliers",
    "description": "Est. 1970. Rocket Arena opened 1994.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg",
    "primary": "#860038",
    "secondary": "#fdbb30",
    "accent": "#ffe1a2",
    "material": "dark"
  },
  "heat": {
    "established": 1988, "venue": "Kaseya Center", "opened": 1999, "titles": 3,
    "name": "Miami Heat",
    "short": "Heat",
    "city": "Miami",
    "sport": "Basketball",
    "label": "Miami Heat",
    "description": "Est. 1988. Kaseya Center opened 1999.",
    "logoSource": "https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg",
    "primary": "#98002e",
    "secondary": "#f9a01b",
    "accent": "#ffd6a1",
    "material": "dark"
  },
  "cowboys": {
    "established": 1960, "venue": "AT&T Stadium", "opened": 2009, "titles": 5,
    "name": "Dallas Cowboys",
    "short": "Cowboys",
    "city": "Dallas",
    "sport": "Football",
    "label": "Dallas Cowboys",
    "description": "Est. 1960. AT&T Stadium opened 2009.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/DAL",
    "primary": "#003594",
    "secondary": "#869397",
    "accent": "#d7e5f7",
    "material": "porcelain"
  },
  "eagles": {
    "established": 1933, "venue": "Lincoln Financial Field", "opened": 2003, "titles": 2,
    "name": "Philadelphia Eagles",
    "short": "Eagles",
    "city": "Philadelphia",
    "sport": "Football",
    "label": "Philadelphia Eagles",
    "description": "Est. 1933. Lincoln Financial Field opened 2003.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/PHI",
    "primary": "#004c54",
    "secondary": "#a5acaf",
    "accent": "#b8eee3",
    "material": "dark"
  },
  "patriots": {
    "established": 1960, "venue": "Gillette Stadium", "opened": 2002, "titles": 6,
    "name": "New England Patriots",
    "short": "Patriots",
    "city": "New England",
    "sport": "Football",
    "label": "NE Patriots",
    "description": "Est. 1960. Gillette Stadium opened 2002.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/NE",
    "primary": "#002244",
    "secondary": "#c60c30",
    "accent": "#cbdfff",
    "material": "dark"
  },
  "chiefs": {
    "established": 1960, "venue": "GEHA Field at Arrowhead Stadium", "opened": 1972, "titles": 4,
    "name": "Kansas City Chiefs",
    "short": "Chiefs",
    "city": "Kansas City",
    "sport": "Football",
    "label": "KC Chiefs",
    "description": "Est. 1960. GEHA Field at Arrowhead Stadium opened 1972.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/KC",
    "primary": "#e31837",
    "secondary": "#ffb81c",
    "accent": "#ffd7a1",
    "material": "dark"
  },
  "steelers": {
    "established": 1933, "venue": "Acrisure Stadium", "opened": 2001, "titles": 6,
    "name": "Pittsburgh Steelers",
    "short": "Steelers",
    "city": "Pittsburgh",
    "sport": "Football",
    "label": "Pittsburgh Steelers",
    "description": "Est. 1933. Acrisure Stadium opened 2001.",
    "logoSource": "https://static.www.nfl.com/t_headshot_desktop/league/api/clubs/logos/PIT",
    "primary": "#171717",
    "secondary": "#ffb612",
    "accent": "#ffe28f",
    "material": "dark"
  },
  "rangers": {
    "established": 1926, "venue": "Madison Square Garden", "opened": 1968, "titles": 4,
    "name": "New York Rangers",
    "short": "Rangers",
    "city": "New York",
    "sport": "Hockey",
    "label": "NY Rangers",
    "description": "Est. 1926. Madison Square Garden opened 1968.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/NYR_dark.svg",
    "primary": "#0038a8",
    "secondary": "#ce1126",
    "accent": "#c9deff",
    "material": "ice"
  },
  "blackhawks": {
    "established": 1926, "venue": "United Center", "opened": 1994, "titles": 6,
    "name": "Chicago Blackhawks",
    "short": "Blackhawks",
    "city": "Chicago",
    "sport": "Hockey",
    "label": "Chicago Blackhawks",
    "description": "Est. 1926. United Center opened 1994.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/CHI_dark.svg",
    "primary": "#cf0a2c",
    "secondary": "#111111",
    "accent": "#ffbdc7",
    "material": "dark"
  },
  "penguins": {
    "established": 1967, "venue": "PPG Paints Arena", "opened": 2010, "titles": 5,
    "name": "Pittsburgh Penguins",
    "short": "Penguins",
    "city": "Pittsburgh",
    "sport": "Hockey",
    "label": "Pittsburgh Penguins",
    "description": "Est. 1967. PPG Paints Arena opened 2010.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/PIT_dark.svg",
    "primary": "#111111",
    "secondary": "#ffb81c",
    "accent": "#ffe399",
    "material": "dark"
  },
  "bruins": {
    "established": 1924, "venue": "TD Garden", "opened": 1995, "titles": 6,
    "name": "Boston Bruins",
    "short": "Bruins",
    "city": "Boston",
    "sport": "Hockey",
    "label": "Boston Bruins",
    "description": "Est. 1924. TD Garden opened 1995.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/BOS_dark.svg",
    "primary": "#111111",
    "secondary": "#ffb81c",
    "accent": "#ffe59f",
    "material": "ice"
  },
  "maple-leafs": {
    "established": 1917, "venue": "Scotiabank Arena", "opened": 1999, "titles": 13,
    "name": "Toronto Maple Leafs",
    "short": "Maple Leafs",
    "city": "Toronto",
    "sport": "Hockey",
    "label": "Toronto Maple Leafs",
    "description": "Est. 1917. Scotiabank Arena opened 1999.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/TOR_dark.svg",
    "primary": "#00205b",
    "secondary": "#ffffff",
    "accent": "#c8ddff",
    "material": "ice"
  },
  "canadiens": {
    "established": 1909, "venue": "Bell Centre", "opened": 1996, "titles": 24,
    "name": "Montreal Canadiens",
    "short": "Canadiens",
    "city": "Montreal",
    "sport": "Hockey",
    "label": "Montreal Canadiens",
    "description": "Est. 1909. Bell Centre opened 1996.",
    "logoSource": "https://assets.nhle.com/logos/nhl/svg/MTL_dark.svg",
    "primary": "#af1e2d",
    "secondary": "#192168",
    "accent": "#ffc6ce",
    "material": "ice"
  },
  "mets": {
    "established": 1962, "venue": "Citi Field", "opened": 2009, "titles": 2,
    "name": "New York Mets", "short": "Mets", "city": "Queens, New York", "sport": "Baseball", "label": "NY Mets",
    "description": "Est. 1962. Citi Field opened 2009.",
    "logoSource": "https://www.mlbstatic.com/team-logos/121.svg",
    "material": "bespoke"
  }
};

export const SPORTS_GROUPS = [
  {
    "id": "baseball",
    "label": "Baseball",
    "themes": [
      "yankees",
      "mets",
      "dodgers",
      "red-sox",
      "blue-jays",
      "cubs"
    ]
  },
  {
    "id": "basketball",
    "label": "Basketball",
    "themes": [
      "knicks",
      "lakers",
      "warriors",
      "bulls",
      "cavaliers",
      "heat"
    ]
  },
  {
    "id": "football",
    "label": "Football",
    "themes": [
      "giants",
      "cowboys",
      "eagles",
      "patriots",
      "chiefs",
      "steelers"
    ]
  },
  {
    "id": "hockey",
    "label": "Hockey",
    "themes": [
      "rangers",
      "blackhawks",
      "penguins",
      "bruins",
      "maple-leafs",
      "canadiens"
    ]
  }
];
